#!/bin/bash

# Script para desplegar todos los servicios Docker en su configuración correcta

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "🚀 Despliegue de Servicios Docker"
echo "=================================="
echo ""

# Step 1: Ensure Traefik network exists
echo "📡 Paso 1: Verificando red Docker..."
NETWORK_NAME="dannig-network"

if ! docker network inspect "$NETWORK_NAME" &>/dev/null; then
  echo "   Creando red $NETWORK_NAME..."
  docker network create "$NETWORK_NAME"
  echo "   ✅ Red creada"
else
  echo "   ✅ Red $NETWORK_NAME existe"
fi

echo ""

# Step 2: Check current Traefik status
echo "📋 Paso 2: Verificando estado de Traefik..."
if docker ps --format "{{.Names}}" | grep -q "^traefik$"; then
  echo "   ✅ Traefik está corriendo"
  TRAEFIK_RUNNING=true
else
  echo "   ⚠️  Traefik no está corriendo"
  TRAEFIK_RUNNING=false
fi

echo ""

# Step 3: Configure m3u8-proxy behind Traefik
echo "🎬 Paso 3: Configurando m3u8-proxy..."
mkdir -p traefik/dynamic-config

cat > traefik/dynamic-config/m3u8-proxy.yml <<'EOF'
# Configuration for m3u8-proxy behind Traefik
# Auto-generated by deploy-services.sh

http:
  middlewares:
    redirect-m3u8-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    m3u8-proxy:
      rule: "Host(`m3u8.Dannig-Optica.freeddns.org`)"
      entryPoints:
        - websecure
      service: m3u8-proxy-svc
      tls:
        certResolver: letsencrypt
      priority: 10
    
    m3u8-proxy-http:
      rule: "Host(`m3u8.Dannig-Optica.freeddns.org`)"
      entryPoints:
        - web
      middlewares:
        - redirect-m3u8-to-https
      service: m3u8-proxy-svc
      priority: 10

  services:
    m3u8-proxy-svc:
      loadBalancer:
        servers:
          - url: "http://m3u8-proxy:80"
EOF

echo "   ✅ Configuración de Traefik creada: traefik/dynamic-config/m3u8-proxy.yml"

# Connect m3u8-proxy to dannig-network if not already connected
if docker ps --format "{{.Names}}" | grep -q "^m3u8-proxy$"; then
  echo "   Conectando m3u8-proxy a la red $NETWORK_NAME..."
  docker network connect "$NETWORK_NAME" m3u8-proxy 2>/dev/null || echo "     (ya está conectado o error al conectar)"
  echo "   ✅ m3u8-proxy configurado"
else
  echo "   ⚠️  m3u8-proxy no está corriendo (se configurará cuando se inicie)"
fi

echo ""

# Step 4: Configure Portainer behind Traefik (optional)
echo "📊 Paso 4: Configurando Portainer (opcional)..."
read -p "   ¿Configurar Portainer detrás de Traefik? (y/n) " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
  cat >> traefik/dynamic-config/portainer.yml <<'EOF'
# Configuration for Portainer behind Traefik

http:
  routers:
    portainer:
      rule: "Host(`portainer.Dannig-Optica.freeddns.org`)"
      entryPoints:
        - websecure
      service: portainer-svc
      tls:
        certResolver: letsencrypt
    
    portainer-http:
      rule: "Host(`portainer.Dannig-Optica.freeddns.org`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: portainer-svc

  services:
    portainer-svc:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"
EOF

  if docker ps --format "{{.Names}}" | grep -q "^portainer$"; then
    docker network connect "$NETWORK_NAME" portainer 2>/dev/null || echo "     (ya está conectado)"
    echo "   ✅ Portainer configurado"
  else
    echo "   ⚠️  Portainer no está corriendo"
  fi
else
  echo "   ⏭️  Saltando Portainer"
fi

echo ""

# Step 5: Ensure Traefik is using correct ports
echo "🔌 Paso 5: Verificando configuración de puertos..."
if [ -f .env ]; then
  HTTP_PORT=$(grep "^TRAEFIK_HTTP_PORT=" .env | cut -d= -f2 || echo "80")
  HTTPS_PORT=$(grep "^TRAEFIK_HTTPS_PORT=" .env | cut -d= -f2 || echo "443")
else
  HTTP_PORT=80
  HTTPS_PORT=443
fi

echo "   Traefik HTTP port: $HTTP_PORT"
echo "   Traefik HTTPS port: $HTTPS_PORT"

if [ "$HTTP_PORT" != "80" ] || [ "$HTTPS_PORT" != "443" ]; then
  echo ""
  echo "   ⚠️  ADVERTENCIA: Let's Encrypt requiere puertos 80 y 443"
  echo "   Si usas puertos personalizados, Let's Encrypt NO funcionará"
  echo ""
  read -p "   ¿Cambiar a puertos 80/443 para Let's Encrypt? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    if [ ! -f .env ]; then
      cat > .env <<EOF
# Traefik Ports Configuration
TRAEFIK_HTTP_PORT=80
TRAEFIK_HTTPS_PORT=443
TRAEFIK_DASHBOARD_PORT=8080

# MySQL Configuration
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=dannig
MYSQL_USER=dannig
MYSQL_PASSWORD=dannig

# Backend Configuration
JWT_SECRET=secure-token-change-in-production
ADMIN_EMAIL=admin@dannig.local
ADMIN_PASSWORD=admin123

# Frontend API URL
VITE_API_URL=https://api.Dannig-Optica.freeddns.org
EOF
    else
      sed -i 's/^TRAEFIK_HTTP_PORT=.*/TRAEFIK_HTTP_PORT=80/' .env
      sed -i 's/^TRAEFIK_HTTPS_PORT=.*/TRAEFIK_HTTPS_PORT=443/' .env
    fi
    echo "   ✅ .env actualizado para usar puertos 80/443"
  fi
fi

echo ""

# Step 6: Stop m3u8-proxy if it's using port 8080 externally
echo "🔧 Paso 6: Verificando puerto 8080..."
if docker ps --format "{{.Names}} {{.Ports}}" | grep -q "m3u8-proxy.*8080"; then
  echo "   m3u8-proxy está usando puerto 8080 externamente"
  echo "   Para usar Traefik, debe moverse a puerto interno solamente"
  echo ""
  read -p "   ¿Detener m3u8-proxy para reconfigurarlo? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "   Deteniendo m3u8-proxy..."
    docker stop m3u8-proxy 2>/dev/null || true
    echo "   ✅ m3u8-proxy detenido"
    echo ""
    echo "   📝 IMPORTANTE: Edita el docker-compose.yml de m3u8-proxy"
    echo "      y elimina o comenta la línea de ports: \"8080:80\""
    echo "      Luego reinícialo con: docker-compose up -d m3u8-proxy"
    echo ""
  fi
fi

echo ""

# Step 7: Start/restart Traefik
echo "🚀 Paso 7: Iniciando/Reiniciando Traefik..."
if [ "$TRAEFIK_RUNNING" = true ]; then
  echo "   Reiniciando Traefik para cargar nueva configuración..."
  docker compose -f docker-compose.traefik.yml restart traefik 2>/dev/null || \
    docker-compose -f docker-compose.traefik.yml restart traefik 2>/dev/null || \
    docker restart dannig-traefik 2>/dev/null
else
  echo "   Iniciando Traefik..."
  docker compose -f docker-compose.traefik.yml up -d traefik 2>/dev/null || \
    docker-compose -f docker-compose.traefik.yml up -d traefik 2>/dev/null
fi

sleep 3

if docker ps --format "{{.Names}}" | grep -q "^traefik$\|^dannig-traefik$"; then
  echo "   ✅ Traefik está corriendo"
else
  echo "   ❌ Error al iniciar Traefik"
  echo "   Verifica los logs: docker compose -f docker-compose.traefik.yml logs traefik"
fi

echo ""

# Step 8: Summary
echo "✅ Despliegue completado!"
echo ""
echo "📋 Resumen de configuración:"
echo ""
echo "   🌐 Servicios disponibles:"
echo "      - DannigOptica Frontend: https://app.Dannig-Optica.freeddns.org"
echo "      - DannigOptica API: https://api.Dannig-Optica.freeddns.org"
if [ -f traefik/dynamic-config/m3u8-proxy.yml ]; then
  echo "      - m3u8-proxy: https://m3u8.Dannig-Optica.freeddns.org"
fi
if [ -f traefik/dynamic-config/portainer.yml ]; then
  echo "      - Portainer: https://portainer.Dannig-Optica.freeddns.org"
fi
echo "      - Traefik Dashboard: https://dashboard.Dannig-Optica.freeddns.org"
echo ""
echo "   🔐 SSL: Let's Encrypt (certificados se emitirán automáticamente)"
echo ""
echo "   📝 Para ver logs:"
echo "      docker compose -f docker-compose.traefik.yml logs -f"
echo ""
echo "   🔄 Para reiniciar todos los servicios:"
echo "      docker compose -f docker-compose.traefik.yml restart"
echo ""

