#!/bin/bash

# Script específico para configurar servicios detectados y habilitar Let's Encrypt

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "🔧 Configuración para Let's Encrypt"
echo "===================================="
echo ""
echo "Servicios detectados:"
echo "  - m3u8-proxy en puerto 8080"
echo "  - Traefik (recién iniciado, posiblemente en 80)"
echo "  - Portainer en 9000/9443"
echo ""

echo "📋 Opciones:"
echo ""
echo "1. Mover m3u8-proxy detrás de Traefik (Recomendado)"
echo "   - m3u8-proxy: https://m3u8.Dannig-Optica.freeddns.org"
echo "   - Con certificado SSL automático"
echo ""
echo "2. Mover m3u8-proxy a puerto alternativo (18080)"
echo "   - Acceso directo: http://IP:18080"
echo "   - Sin SSL automático"
echo ""
echo "3. Solo verificar estado actual"
echo ""

read -p "Selecciona opción (1-3): " option

case $option in
  1)
    echo ""
    echo "🔧 Configurando m3u8-proxy detrás de Traefik..."
    echo ""
    
    # Create dynamic route for m3u8-proxy
    mkdir -p traefik/dynamic-config
    
    cat > traefik/dynamic-config/m3u8-proxy.yml <<EOF
# Configuration for m3u8-proxy behind Traefik
# Generated by fix-services-for-letsencrypt.sh

http:
  routers:
    m3u8-proxy:
      rule: "Host(\`m3u8.Dannig-Optica.freeddns.org\`)"
      entryPoints:
        - websecure
      service: m3u8-proxy-svc
      tls:
        certResolver: letsencrypt
    m3u8-proxy-http:
      rule: "Host(\`m3u8.Dannig-Optica.freeddns.org\`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: m3u8-proxy-svc

  services:
    m3u8-proxy-svc:
      loadBalancer:
        servers:
          - url: "http://m3u8-proxy:80"
EOF

    echo "✅ Configuración creada: traefik/dynamic-config/m3u8-proxy.yml"
    echo ""
    echo "📝 Próximos pasos:"
    echo ""
    echo "1. Asegúrate de que m3u8-proxy y traefik estén en la misma red Docker:"
    echo "   docker network connect dannig-network m3u8-proxy"
    echo ""
    echo "2. O configura m3u8-proxy para no exponer el puerto 8080:"
    echo "   (Edita su docker-compose.yml y elimina la línea de ports para 8080)"
    echo ""
    echo "3. Reinicia Traefik para cargar la nueva configuración:"
    echo "   docker compose -f docker-compose.traefik.yml restart traefik"
    echo ""
    echo "4. Accede a m3u8-proxy en:"
    echo "   https://m3u8.Dannig-Optica.freeddns.org"
    echo ""
    ;;
    
  2)
    echo ""
    echo "📝 Instrucciones para mover m3u8-proxy a puerto 18080:"
    echo ""
    echo "1. Detener m3u8-proxy:"
    echo "   docker stop m3u8-proxy"
    echo ""
    echo "2. Editar el docker-compose.yml de m3u8-proxy"
    echo "   Cambiar: \"8080:80\" → \"18080:80\""
    echo ""
    echo "3. Reiniciar:"
    echo "   docker-compose up -d m3u8-proxy"
    echo ""
    echo "4. Verificar que el puerto 80 esté libre:"
    echo "   ss -tuln | grep ':80 '"
    echo ""
    echo "5. Iniciar Traefik con Let's Encrypt:"
    echo "   ./start-traefik.sh"
    echo ""
    ;;
    
  3)
    echo ""
    echo "🔍 Estado actual:"
    echo ""
    echo "Contenedores Docker:"
    docker ps --format "  - {{.Names}}: {{.Ports}}" 2>/dev/null | grep -E "(m3u8|traefik|portainer)" || echo "  No encontrados"
    echo ""
    echo "Puertos en uso:"
    ss -tuln 2>/dev/null | grep -E ':(80|443|8080) ' | while read line; do
      echo "  $line"
    done
    echo ""
    echo "Para ver más detalles:"
    echo "  ./detect-running-services.sh"
    echo ""
    ;;
    
  *)
    echo "❌ Opción inválida"
    exit 1
    ;;
esac

echo ""
echo "💡 Recordatorio:"
echo "   - Puerto 80 debe estar libre para Let's Encrypt"
echo "   - Puerto 443 debe estar libre para HTTPS"
echo "   - Los servicios pueden seguir funcionando detrás de Traefik"
echo ""

