#!/bin/bash

# Script para migrar servicios existentes y permitir que Traefik use Let's Encrypt
# Este script detecta servicios en puertos 80/443 y ayuda a reubicarlos

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "🔄 Migración de Servicios para Let's Encrypt"
echo "=============================================="
echo ""

# Check if running as root for port detection
if [ "$EUID" -ne 0 ] && ! sudo -n true 2>/dev/null; then
  echo "⚠️  Este script necesita permisos de administrador para detectar servicios"
  echo "   Se ejecutará con sudo cuando sea necesario"
  echo ""
fi

# Function to detect services on ports
detect_port_usage() {
  local port=$1
  local services=()
  
  if sudo ss -tulpn 2>/dev/null | grep -q ":${port} "; then
    sudo ss -tulpn 2>/dev/null | grep ":${port} " | while read line; do
      pid=$(echo "$line" | grep -oP 'pid=\K[0-9]+')
      process=$(ps -p "$pid" -o comm= 2>/dev/null || echo "unknown")
      echo "$process (PID: $pid)"
    done
  fi
}

echo "🔍 Detectando servicios en puertos 80 y 443..."
echo ""

PORT80_SERVICES=$(sudo ss -tulpn 2>/dev/null | grep ":80 " | head -5 || echo "")
PORT443_SERVICES=$(sudo ss -tulpn 2>/dev/null | grep ":443 " | head -5 || echo "")

if [ -n "$PORT80_SERVICES" ]; then
  echo "⚠️  Puerto 80 está en uso:"
  echo "$PORT80_SERVICES" | while read line; do
    echo "   $line"
  done
  echo ""
fi

if [ -n "$PORT443_SERVICES" ]; then
  echo "⚠️  Puerto 443 está en uso:"
  echo "$PORT443_SERVICES" | while read line; do
    echo "   $line"
  done
  echo ""
fi

if [ -z "$PORT80_SERVICES" ] && [ -z "$PORT443_SERVICES" ]; then
  echo "✅ Los puertos 80 y 443 están libres!"
  echo ""
  echo "Puedes usar Let's Encrypt directamente con:"
  echo "  ./start-traefik.sh"
  exit 0
fi

echo "💡 Opciones para liberar puertos 80 y 443:"
echo ""
echo "1. Mover servicios existentes a puertos alternativos"
echo "2. Configurar Traefik como proxy único y mover servicios detrás de él"
echo "3. Usar port forwarding con iptables (avanzado)"
echo ""
read -p "Selecciona una opción (1-3): " choice

case $choice in
  1)
    echo ""
    echo "📝 Opción 1: Mover servicios a puertos alternativos"
    echo ""
    echo "Necesitarás:"
    echo "- Identificar qué servicios usan 80/443"
    echo "- Modificar su configuración para usar puertos alternativos"
    echo "- Actualizar cualquier referencia a esos servicios"
    echo ""
    echo "Puertos recomendados:"
    echo "  - HTTP alternativo: 8080, 8888, 9000"
    echo "  - HTTPS alternativo: 8443, 9443"
    echo ""
    read -p "¿Continuar? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      echo ""
      echo "📋 Siguiente: Edita manualmente la configuración de tus servicios"
      echo "   y muévelos a puertos alternativos, luego ejecuta ./start-traefik.sh"
    fi
    ;;
    
  2)
    echo ""
    echo "📝 Opción 2: Traefik como Proxy Único"
    echo ""
    echo "Esta opción configura Traefik para:"
    echo "- Recibir todo el tráfico en 80/443"
    echo "- Enrutar a servicios existentes por hostname/path"
    echo "- Usar Let's Encrypt para certificados SSL"
    echo ""
    
    # Ask for existing services
    echo "¿Qué servicios quieres mantener detrás de Traefik?"
    echo ""
    read -p "Servicio 1 hostname (ej: servicio1.local): " host1
    read -p "Servicio 1 puerto interno (ej: 8001): " port1
    read -p "Servicio 1 path opcional (ej: /app o dejar vacío): " path1
    
    echo ""
    echo "Creando configuración de Traefik para servicio existente..."
    
    # Create additional traefik config
    cat > traefik/dynamic-routes.yml <<EOF
# Dynamic routes for existing services
# Generated by migrate-services.sh

http:
  routers:
    existing-service-1:
      rule: "Host(\`${host1}\`)${path1:+ && PathPrefix(\`${path1}\`)}"
      entryPoints:
        - websecure
      service: existing-service-1-svc
      tls:
        certResolver: letsencrypt
    existing-service-1-http:
      rule: "Host(\`${host1}\`)${path1:+ && PathPrefix(\`${path1}\`)}"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: existing-service-1-svc

  services:
    existing-service-1-svc:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:${port1}"
EOF

    echo "✅ Configuración creada en traefik/dynamic-routes.yml"
    echo ""
    echo "Nota: Necesitarás:"
    echo "1. Asegurar que el servicio en puerto ${port1} está accesible desde Docker"
    echo "2. Agregar el volumen a docker-compose.traefik.yml:"
    echo "   - ./traefik/dynamic-routes.yml:/dynamic-routes.yml:ro"
    echo "3. Agregar al comando de Traefik:"
    echo "   - \"--providers.file.filename=/dynamic-routes.yml\""
    echo ""
    ;;
    
  3)
    echo ""
    echo "📝 Opción 3: Port Forwarding con iptables"
    echo ""
    echo "Esta opción usa iptables para redirigir:"
    echo "- Puerto 80 → Servicio existente (puerto alternativo)"
    echo "- Puerto 443 → Traefik (para Let's Encrypt)"
    echo ""
    echo "⚠️  Requiere permisos root y configuración manual de iptables"
    echo ""
    read -p "¿Continuar con configuración manual? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      echo ""
      echo "Ejemplo de reglas iptables:"
      echo ""
      echo "# Redirigir HTTP (80) a servicio en 8080"
      echo "sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080"
      echo ""
      echo "# Permitir que Traefik escuche en 443"
      echo "# (Traefik se configura normalmente en docker-compose)"
      echo ""
      echo "⚠️  Estas reglas se perderán al reiniciar. Considera hacerlas persistentes."
    fi
    ;;
    
  *)
    echo "❌ Opción inválida"
    exit 1
    ;;
esac

echo ""
echo "✅ Configuración completada"
echo ""
echo "Siguiente paso: Ejecuta ./start-traefik.sh para iniciar con Let's Encrypt"

