#!/bin/bash

# Script para configurar Traefik como proxy único
# Mueve servicios existentes detrás de Traefik manteniendo 80/443 para Let's Encrypt

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "🚀 Configuración de Traefik como Proxy Único"
echo "============================================="
echo ""
echo "Este script configura Traefik para:"
echo "✅ Usar puertos 80/443 (para Let's Encrypt)"
echo "✅ Enrutar servicios existentes por hostname"
echo "✅ Mantener servicios de DannigOptica"
echo ""

# Check if docker-compose.traefik.yml exists
if [ ! -f docker-compose.traefik.yml ]; then
  echo "❌ docker-compose.traefik.yml no encontrado"
  exit 1
fi

# Create dynamic routes file
mkdir -p traefik/dynamic-config
DYNAMIC_ROUTES_FILE="traefik/dynamic-config/existing-services.yml"

echo "📝 Configurando rutas dinámicas..."
echo ""

# Ask for existing services
echo "¿Qué servicios quieres enrutar a través de Traefik?"
echo "(Deja vacío para solo usar servicios de DannigOptica)"
echo ""

SERVICES_COUNT=0
declare -a SERVICE_HOSTS
declare -a SERVICE_PORTS
declare -a SERVICE_PATHS

while true; do
  read -p "Hostname del servicio (ej: otro-servicio.local) o 'fin' para terminar: " hostname
  
  if [ "$hostname" = "fin" ] || [ -z "$hostname" ]; then
    break
  fi
  
  read -p "Puerto interno del servicio (ej: 8080): " port
  read -p "Path opcional (ej: /app o dejar vacío): " path
  
  SERVICE_HOSTS[$SERVICES_COUNT]=$hostname
  SERVICE_PORTS[$SERVICES_COUNT]=$port
  SERVICE_PATHS[$SERVICES_COUNT]=${path:-}
  
  SERVICES_COUNT=$((SERVICES_COUNT + 1))
  echo ""
done

# Generate dynamic routes configuration
cat > "$DYNAMIC_ROUTES_FILE" <<'EOF'
# Dynamic routes for existing services
# This file is automatically generated by setup-traefik-proxy.sh
# Add your custom routes here

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
EOF

# Add routes for each service
for i in $(seq 0 $((SERVICES_COUNT - 1))); do
  host=${SERVICE_HOSTS[$i]}
  port=${SERVICE_PORTS[$i]}
  path=${SERVICE_PATHS[$i]}
  
  service_name=$(echo "$host" | tr '.' '-' | tr '[:upper:]' '[:lower:]')
  
  cat >> "$DYNAMIC_ROUTES_FILE" <<EOF

  routers:
    ${service_name}:
      rule: "Host(\`${host}\`)${path:+ && PathPrefix(\`${path}\`)}"
      entryPoints:
        - websecure
      service: ${service_name}-svc
      tls:
        certResolver: letsencrypt
    ${service_name}-http:
      rule: "Host(\`${host}\`)${path:+ && PathPrefix(\`${path}\`)}"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: ${service_name}-svc

  services:
    ${service_name}-svc:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:${port}"
EOF
done

echo "✅ Configuración creada en $DYNAMIC_ROUTES_FILE"
echo ""

# Check if docker-compose is already configured
if ! grep -q "dynamic-config" docker-compose.traefik.yml; then
  echo "⚠️  docker-compose.traefik.yml necesita ser actualizado manualmente"
  echo "   (Ya debería estar configurado, pero verifica)"
  echo ""
fi

# Create helper script to stop services on ports 80/443
cat > stop-existing-services.sh <<'EOF'
#!/bin/bash
# Helper script to stop services on ports 80 and 443
# WARNING: This will stop processes using these ports

echo "⚠️  Deteniendo servicios en puertos 80 y 443..."
echo ""

for port in 80 443; do
  pids=$(sudo ss -tulpn 2>/dev/null | grep ":${port} " | grep -oP 'pid=\K[0-9]+' | sort -u)
  
  if [ -n "$pids" ]; then
    echo "Puerto $port:"
    for pid in $pids; do
      process=$(ps -p "$pid" -o comm= 2>/dev/null || echo "unknown")
      echo "  - PID $pid ($process)"
      read -p "¿Detener este proceso? (y/n) " -n 1 -r
      echo
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        sudo kill "$pid" 2>/dev/null || echo "   No se pudo detener PID $pid"
      fi
    done
  fi
done

echo ""
echo "✅ Proceso completado"
EOF

chmod +x stop-existing-services.sh

echo "📋 Resumen de configuración:"
echo ""
echo "✅ Archivo de rutas dinámicas: $DYNAMIC_ROUTES_FILE"
echo "✅ docker-compose.traefik.yml actualizado"
echo "✅ Script helper creado: stop-existing-services.sh"
echo ""
echo "📝 Próximos pasos:"
echo ""
echo "1. Si tienes servicios corriendo en 80/443, detenlos:"
echo "   ./stop-existing-services.sh"
echo ""
echo "2. O reconfigúralos para usar puertos alternativos"
echo ""
echo "3. Inicia Traefik con Let's Encrypt:"
echo "   ./start-traefik.sh"
echo ""
echo "4. Accede a tus servicios:"
for i in $(seq 0 $((SERVICES_COUNT - 1))); do
  host=${SERVICE_HOSTS[$i]}
  echo "   - https://${host}"
done
echo "   - https://app.Dannig-Optica.freeddns.org (Frontend)"
echo "   - https://api.Dannig-Optica.freeddns.org (Backend)"
echo ""

